/* DAVID GUIJO LOPEZ */

/*TABLA MATERIAL*/
CREATE TABLE DGL_MATERIAL(
COD_MATERIAL NUMBER(5),
NOMBRE VARCHAR2(15),
PRECIO NUMBER(3),

CONSTRAINT MAT_COD_PK PRIMARY KEY (COD_MATERIAL)
);


/*TABLA NECESITA*/
CREATE TABLE DGL_NECESITA(
CANTIDAD NUMBER(4),
COD_OPERACION NUMBER(5),
COD_MATERIAL NUMBER(5),

CONSTRAINT NEC_COD_PK PRIMARY KEY(COD_OPERACION,COD_MATERIAL),

CONSTRAINT NEC_CODOP_FK FOREIGN KEY(COD_OPERACION)
    REFERENCES DGL_OPERACION,
CONSTRAINT NEC_CODMAT_FK FOREIGN KEY(COD_MATERIAL)
    REFERENCES DGL_MATERIAL
);


/*TABLA OPERACION*/
CREATE TABLE DGL_OPERACION(
COD_OPERACION NUMBER(5),
DESCRIPCION VARCHAR2(50),
HORAS TIMESTAMP,

CONSTRAINT OPE_CODOP_PK PRIMARY KEY(COD_OPERACION)
);


/*TABLA CONSTA DE*/
CREATE TABLE DGL_CONSTADE(
COD_OPERACION NUMBER(5),
COD_REVISION NUMBER(5),

CONSTRAINT CONS_COD_PK PRIMARY KEY(COD_OPERACION,COD_REVISION),

CONSTRAINT CONS_CODOP_FK FOREIGN KEY(COD_OPERACION)
    REFERENCES DGL_OPERACION,
CONSTRAINT CONS_CODRE_FK FOREIGN KEY(COD_REVISION)
    REFERENCES DGL_REVISION
);


/*TABLA REVISION*/
CREATE TABLE DGL_REVISION(
COD_REVISION NUMBER(5),
FECHA DATE,
MATRICULA VARCHAR2(7),

CONSTRAINT REV_CODRE_PK PRIMARY KEY(COD_REVISION),

CONSTRAINT REV_MAT_FK FOREIGN KEY(MATRICULA)
    REFERENCES DGL_COCHE ON DELETE CASCADE
);


/*TABLA COCHE*/
CREATE TABLE DGL_COCHE(
MATRICULA VARCHAR2(7),
MARCA VARCHAR2(15),
COLOR VARCHAR2(12),
MODELO VARCHAR2(15),
PVP NUMBER(6),
COD_CLIENTE NUMBER(4),

CONSTRAINT COC_MAT_PK PRIMARY KEY(MATRICULA),

CONSTRAINT COC_COD_FK FOREIGN KEY(COD_CLIENTE)
    REFERENCES DGL_CLIENTE ON DELETE CASCADE
);


/*TABLA CLIENTE*/
CREATE TABLE DGL_CLIENTE(
COD_CLIENTE NUMBER(4),
NIF VARCHAR2(9),
CIUDAD VARCHAR2(20),
NOMBRE VARCHAR2(15),
DIRECCION VARCHAR2(20),
TELEFONO NUMBER(9),

CONSTRAINT CLI_COD_PK PRIMARY KEY(COD_CLIENTE)
);