/*DAVID GUIJO LOPEZ*/

/*EJERCICIO 1*/
CREATE OR REPLACE VIEW LISTADO_COMERCIAL_PEDIDOS AS(
SELECT T1.NOMBRE||' '||T1.APELLIDO1||' '||T1.APELLIDO2 AS "COMERCIAL", T2.ID AS "ID_PEDIDO",T2.FECHA AS "FECHA_PEDIDO"
FROM COMERCIAL T1 JOIN PEDIDO T2 ON T1.ID=T2.ID_COMERCIAL
);


/*EJERCICIO 2*/
SELECT *
FROM LISTADO_COMERCIAL_PEDIDOS T1 JOIN COMERCIAL T2 ON T1.ID_PEDIDO=T2.ID
WHERE T1.ID_PEDIDO!=T2.ID;


/*EJERCICIO 3*/
SELECT *
FROM LISTADO_COMERCIAL_PEDIDOS
WHERE COMERCIAL='Daniel Saez Vega';


/*EJERCICIO 4*/
SELECT T1.COMERCIAL,T2.TOTAL
FROM LISTADO_COMERCIAL_PEDIDOS T1 JOIN PEDIDO T2 ON T1.ID_PEDIDO=T2.ID
WHERE T2.TOTAL>2000.00;
