version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: tienda
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    command: bash -c "docker-php-ext-install mysqli pdo_mysql && docker-php-ext-enable mysqli pdo_mysql && apache2-foreground"


  db:
    image: mysql:5.7
    container_name: tienda_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=shop_db
      - MYSQL_USER=shop_user
      - MYSQL_PASSWORD=shoppass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

