version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: prueba
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    command: bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql && apache2-foreground"


  db:
    image: postgres:13
    container_name: db_data
    environment:
    -   POSTGRES_DB=biblioteca_db
    -   POSTGRES_USER=biblioteca_user
    -   POSTGRES_PASSWORD=user_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

