
CREATE OR REPLACE PROCEDURE CIUDADDGL (CIUDADCLI CLIENTE.CIUDAD%TYPE) AS
    NOMBRECLI CLIENTE.NOMBRE%TYPE;
    FECHAPEDIDO PEDIDO.FECHA%TYPE;
    TOTAL PEDIDO.TOTAL%TYPE;
    TOTALPEDIDOS NUMBER;
    VALORMEDIO PEDIDO.TOTAL%TYPE;
    VALORMINIMO PEDIDO.TOTAL%TYPE;
    VALORMAXIMO PEDIDO.TOTAL%TYPE;
BEGIN

SELECT T1.NOMBRE,T2.FECHA,T2.TOTAL INTO NOMBRECLI,FECHAPEDIDO,TOTAL
FROM CLIENTE T1 JOIN PEDIDO T2 ON T1.ID=T2.ID_CLIENTE
WHERE T1.CIUDAD = CIUDADCLI;

SELECT COUNT(*),MAX(TOTAL),AVG(TOTAL),MIN(TOTAL) INTO TOTALPEDIDOS,VALORMAXIMO,VALORMEDIO,VALORMINIMO
FROM CLIENTE T1 JOIN PEDIDO T2 ON T1.ID=T2.ID_CLIENTE
WHERE T1.CIUDAD=CIUDADCLI;

    DBMS_OUTPUT.PUT_LINE('Los clientes de '||CIUDADCLI||' que han realizado pedidos son: ');
    DBMS_OUTPUT.PUT_LINE(NOMBRECLI||' '||TOTAL||' '||FECHAPEDIDO);
    
    DBMS_OUTPUT.PUT_LINE('Hay un total de '||TOTALPEDIDOS||' pedidos');
    DBMS_OUTPUT.PUT_LINE('El valor medio de los productos es '||VALORMEDIO);
    DBMS_OUTPUT.PUT_LINE('El valor minimo de los productos es '||VALORMEDIO);
    DBMS_OUTPUT.PUT_LINE('El valor maximo de los productos es '||VALORMEDIO);

EXCEPTION
    WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('No tenemos clientes en '||CIUDADCLI);
END;
/
